- id: cargo-fmt
  name: cargo fmt
  description: Format rust files with cargo fmt
  entry: pre_commit_rust fmt
  language: python
  types: [rust]
  minimum_pre_commit_version: 2.9.2
  require_serial: true
- id: cargo-check
  name: cargo check
  description: Run cargo check for compilation errors
  entry: pre_commit_rust check
  language: python
  types: [rust]
  minimum_pre_commit_version: 2.9.2
  require_serial: true
- id: cargo-clippy
  name: cargo clippy
  description: Run cargo clippy lint tool
  entry: pre_commit_rust clippy
  language: python
  types: [rust]
  minimum_pre_commit_version: 2.9.2
  require_serial: true
