[package]
name = "pre-commit-rust"
version = "0.3.0"
edition = "2021"
authors = ["Kyle Kosic <kylekosic@gmail.com>"]

[[bin]]
name = "pre_commit_rust"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.1.13", features = ["derive"] }
glob = "0.3.1"
